/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GreetingRouteImport } from './routes/greeting'
import { Route as IndexRouteImport } from './routes/index'

const GreetingRoute = GreetingRouteImport.update({
  id: '/greeting',
  path: '/greeting',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/greeting': typeof GreetingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/greeting': typeof GreetingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/greeting': typeof GreetingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/greeting'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/greeting'
  id: '__root__' | '/' | '/greeting'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GreetingRoute: typeof GreetingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/greeting': {
      id: '/greeting'
      path: '/greeting'
      fullPath: '/greeting'
      preLoaderRoute: typeof GreetingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GreetingRoute: GreetingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
